#!/bin/bash
#########################################################################
########COLOR SCHEME FOR FOLDERS and some misc icons
#########################################################################

#  -not -type l   stand for  exclude symbolic links
# -print0 mette tutto in una unica riga per xargs che invierà a sed


newdarkcolor=829fa9
newlightcolor=aad0de
trashemptydark=999999
trashemptylight=ababab

#Dark Base
#e9a439    with    #newdarkcolor
find . -name "*.svg" -not -type l -print0 | xargs -0 sed -i s/e9a439/$newdarkcolor/g


#Light Base
#f5c14e    with    #newlightcolor
find . -name "*.svg" -not -type l -print0 | xargs -0 sed -i s/f5c14e/$newlightcolor/g


#########################################################################
##################COLOR SCHEME FOR THE REMAINING STUFF###################
#########################################################################

#distro logo
find . -name "*.svg" -not -type l -print0 | xargs -0 sed -i s/dc322f/$newlightcolor/g


#trash full
find . -name "*.svg" -not -type l -print0 | xargs -0 sed -i s/d1533e/$newdarkcolor/g
find . -name "*.svg" -not -type l -print0 | xargs -0 sed -i s/f47b67/$newlightcolor/g

#trash empty
find . -name "*.svg" -not -type l -print0 | xargs -0 sed -i s/63b6d1/$trashemptydark/g
find . -name "*.svg" -not -type l -print0 | xargs -0 sed -i s/a2d7e9/$trashemptylight/g
