#!/bin/bash

# gnome-split
sudo sed -i 's/Icon=\/usr\/share\/pixmaps\/gnome-split.png/Icon=gnome-split/g' /usr/share/applications/gnome-split.desktop

# gtk-splitter
sudo sed -i 's/Icon=gtk-splitter.png/gtk-splitter/g'  /usr/share/applications/gtk-splitter.desktop

# gprename
sudo sed -i 's/Icon=\/usr\/share\/pixmaps\/gprename\/gprename.png/Icon=gprename/g' /usr/share/applications/gprename.desktop

# deborphan
sudo sed -i 's/Icon=\/usr\/share\/pixmaps\/gtkorphan.png/Icon=gtkorphan/g' /usr/share/applications/gtkorphan.desktop

# qt4-fsarchiver
sudo sed -i 's/Icon=\/usr\/share\/pixmaps\/harddrive.png/Icon=qt4-fsarchiver/g' /usr/share/applications/qt4-fsarchiver.desktop
sudo sed -i 's/Icon=\/usr\/share\/app-install\/icons\/harddrive.png/Icon=qt4-fsarchiver/g' /usr/share/applications/qt4-fsarchiver.desktop

# pyrenamer
sudo sed -i 's/\/usr\/share\/pyrenamer\/pyrenamer.png/pyrenamer/g' /usr/share/applications/pyrenamer.desktop
